version: '3'
services:

  neo4j:
    build:
      context: ./
      dockerfile: neo4j-dockerfile
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ~/container-volumes/mycelium/neo4j/data:/data
      - ~/container-volumes/mycelium/neo4j/logs:/logs
      - ~/container-volumes/mycelium/neo4j/import:/import
    networks:
      - default
      - fern_default
    external_links:
      - fern_postgres_1:fern_db
    environment:
      NEO4J_AUTH: none
      # NEO4J_dbms_allowFormatMigration: "true"
      NEO4J_dbms_memory_pagecache_size: "1G"
      NEO4J_dbms_memory_heap_maxSize: "2G"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_apoc_export_file_enabled: "true"

  scripts:
    build:
      context: ./
    depends_on:
      - neo4j
    volumes:
      - ./:/app_root/
    command: "rake -T"

networks:
  fern_default:
    external: true

