test:
  type: http
  url: <%= ENV.fetch('NEO4J_URL') { 'http://neo4j_test:7474/db/data' } %>

development:
  type: http
  url: <%= ENV.fetch('NEO4J_URL') { 'http://neo4j:7474/db/data' } %>

production:
  type: http
  url: <%= ENV.fetch('NEO4J_URL') { 'YOU_MUST_SET_NEO4J_URL' } %>
